pipeline {
    agent any
    environment {
        DOCKER_HUB_REPO = 'eliza22/your-repo-name' // Replace with your Docker Hub repository name
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://your-repository-url.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build(DOCKER_HUB_REPO, '.')
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    script {
                        docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                            def customImage = docker.build(DOCKER_HUB_REPO)
                            customImage.push()
                        }
                    }
                }
            }
        }
        stage('Deploy with Docker Compose') {
            steps {
                script {
                    sh 'docker-compose up -d'
                }
            }
        }
    }
}
