pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Eliza-2202/jenkins.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build('eliza22/mi_imagen', './')
                }
            }
        }
        stage('Deploy with Docker Compose') {
            steps {
                script {
                    sh 'docker-compose up -d'
                }
            }
        }
    }
}

