pipeline {
    agent any  // Usa cualquier nodo disponible

    stages {
        stage('Ejecutar') {
            steps {
                script {
                    // Imprimir "Hola Mundo" en la consola
                    echo 'Hola Mundo'
                }
            }
        }
    }
}

