pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "eliza22/suerte:tag"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                dir('dockerKuberMini_File') {  // Cambiar al directorio correcto
                    script {
                        sh 'docker build -t $DOCKER_IMAGE -f Dockerfile .'
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('dockerKuberMini_File') {  // Cambiar al directorio correcto
                    script {
                        sh 'eval $(minikube -p minikube docker-env)'
                        sh 'kubectl apply -f deployment.yml --validate=false'
                    }
                }
            }
        }

        stage('Check Application') {
            steps {
                script {
                    sh 'minikube service fastapi-service --url'
                }
            }
        }
    }

    post {
        always {
            dir('dockerKuberMini_File') {
                sh 'kubectl delete -f deployment.yml || true'
            }
        }
    }
}

