apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80       # Puerto del servicio dentro del clúster
      targetPort: 8000  # Puerto del contenedor FastAPI
      nodePort: 30382  # Puerto que expone el servicio externamente

