pipeline {
    agent { dockerfile true}
    stages {
        stage('Ejecutar') {
            steps {
                script {
                    // Imprimir "Hola Mundo" en la consola
                    echo 'Hola Mundo, holisssssssssss'
                }
            }
        }
    }
}

