pipeline {
    	agent { dockerfile true}
    	stages{
		stage('Test') {
		    steps {
		    	echo 'Hola Mundo, holisssssssssss'
		    }
		}
	       
		stage('Docker Build') {
		      agent any
		      steps {
			sh 'docker build -t shanem/spring-petclinic:latest .'
		      }
		    }
	    	
		stage('Docker Run') {
		      agent any
		      steps {
			sh 'docker run --name test -d eliza22/fastapi-app .'
		      }
		    }
    	}
}

