pipeline {
    agent { dockerfile true}
    stages {
        stage('Test') {
            steps (
            	sh "echo 'Hola Mundo, holisssssssssss'"
            )
        }
       
    }
}

