pipeline {
    agent any

    stages {
        stage('Start Minikube') {
            steps {
                script {
                    // Iniciar Minikube si no está corriendo
                    sh 'minikube start || echo "Minikube ya está corriendo."'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t eliza22/abc:tag -f dockerKuberMini_File/Dockerfile dockerKuberMini_File'
                }
            }
        }

        stage('Load Image into Minikube') {
            steps {
                script {
                    sh 'minikube image load eliza22/abc:tag'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh 'kubectl apply -f deployment.yml'
                    sh 'kubectl apply -f service.yml'
                }
            }
        }

        stage('Check Services') {
            steps {
                script {
                    sh 'kubectl get services'
                }
            }
        }

        stage('Verify Pods') {
            steps {
                script {
                    sh 'kubectl get pods'
                }
            }
        }
    }
}

