pipeline {
    agent any

    environment {
        // Ajusta el nombre de la imagen según sea necesario
        DOCKER_IMAGE = 'img-123'
    }

    stages {
        stage('Clone Repository') {
            steps {
                // Clonar tu repositorio
                git 'https://github.com/Eliza-2202/jenkins.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Cambia al contexto de Docker de Minikube
                    sh 'eval $(minikube docker-env)'

                    // Construye la imagen de Docker
                    sh "docker build -t ${DOCKER_IMAGE} ."
                }
            }
        }

        stage('Deploy to Minikube') {
            steps {
                script {
                    // Aplica el archivo de despliegue en Kubernetes
                    sh 'kubectl apply -f deployment.yaml'
                }
            }
        }
    }

    post {
        always {
            // Limpiar el entorno después de la ejecución
            cleanWs()
        }
    }
}


