apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  ports:
    - port: 80       # Puerto del servicio
      targetPort: 80 # Puerto en el contenedor
      nodePort: 30080  # Puerto NodePort - rango válido para NodePorts en Kubernetes, que es de 30000 a 32767
  selector:
    app: fastapi
